/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
add_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a + argp->b;
	return &result;
}

int *
sub_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a - argp->b;

	return &result;
}

int *
mult_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a * argp->b;

	return &result;
}

int *
div_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a / argp->b;

	return &result;
}
