/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct CMD_INPUT {
	char cmd_input[128];
};
typedef struct CMD_INPUT CMD_INPUT;

#define CALC 120180389
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATION 1
extern  int * calculation_1(CMD_INPUT *, CLIENT *);
extern  int * calculation_1_svc(CMD_INPUT *, struct svc_req *);
extern int calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATION 1
extern  int * calculation_1();
extern  int * calculation_1_svc();
extern int calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_CMD_INPUT (XDR *, CMD_INPUT*);

#else /* K&R C */
extern bool_t xdr_CMD_INPUT ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
